# Generated by Django 3.1 on 2021-05-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_remove_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='city',
            field=models.CharField(choices=[('Ак-Джол', 'Ак-Джол'), ('Ананьево', 'Ананьево'), ('Ат-Башы', 'Ат-Башы'), ('Балыкчы', 'Балыкчы'), ('Бишкек', 'Бишкек'), ('Каракол', 'Каракол'), ('Чолпон-Ата', 'Чолпон-Ата'), ('Кара-Балта', 'Кара-Балта'), ('Токмок', 'Токмок'), ('Нарын', 'Нарын'), ('Талас', 'Талас'), ('Ош', 'Ош'), ('Джалал-Абад', 'Джалал-Абад')], default=1, max_length=50, verbose_name='City'),
            preserve_default=False,
        ),
    ]
